apiVersion: v1
kind: Service
metadata:
  name: threads-service
  labels:
    app: threads-service
spec:
  selector:
    app: threads-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP