apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-deployment
  labels:
    app: posts-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts-deployment
  template:
    metadata:
      labels:
        app: posts-deployment
    spec:
      containers:
      - name: posts-deployment-container
        image: soumyahe/posts-service:latest
        ports:
        - containerPort: 3000