apiVersion: v1
kind: Service
metadata:
  name: posts-service
  labels:
    app: posts-service
spec:
  selector:
    app: posts-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP