apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
  labels:
    app: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-deployment
  template:
    metadata:
      labels:
        app: users-deployment
    spec:
      containers:
      - name: users-deployment-container
        image: soumyahe/users-service:latest
        ports:
        - containerPort: 3000